### ISSUE TITLE
config.json文件在哪？

### ISSUE THREAD

**Issue by mcattx** [Jeff2Ma/JGulp#1]
`gulpfile.js`文件中的`config     = require('./config.json');`引用的config.json找不到在哪里。
`tiny-lr`、`gulp-webserve`和`gulp-livereload`三个包的用法不是不懂。=.=

**Comment by Jeff2Ma** [comment]
@titancat `config.json` 直接自己新建在项目文件下，即与 `gulpfile.js`同一级文件目录。其他的我相信你有仔细看readme 并结合并结合其他资料说明就能搞明白的了。

**Comment by mcattx** [comment]
@Jeff2Ma  
我只是想看一下`config.json`这个怎么配置而已 +.+

```
{
  "localserver": {
    "host": "127.0.0.1",
    "port": "35729"
  }
}

```

我还是去看那三个包的官方文档算了。

**Comment by Jeff2Ma** [comment]
@titancat  `config.json` 的如何配置readme 有个demo，请仔细看哦~
