### ISSUE TITLE
为什么buildfiles在其他动作之后？

### ISSUE THREAD

**Issue by lynnic26** [Jeff2Ma/JGulp#2]
不是应该先建立发布目录（build），然后再run各种压缩合并处理吗？

**Comment by lynnic26** [comment]
可否写一下目录构建方面的思路，目录看不太明白

**Comment by Jeff2Ma** [comment]
@lynnic26 buildfiles 这个任务是指复制相关已经压缩好的静态文件到bulid 目录下，当然得在其他任务之后啦
