### ISSUE TITLE
关于分开打包的问题

### ISSUE THREAD

**Issue by wenzi0github** [Jeff2Ma/JGulp#6]
你好，看了下你的`gulpfile.js`，你是把所有的js的进行打包和压缩，那有没有一种方式，对js，css，img等按照页面分别进行打包，比如js的文件里有`index`, `detail`, `login`等文件夹，每个文件夹都着自己页面的js，分别对index, detail和login里的js进行打包，然后生成：index.min.js, detail.min.js和login.min.js呢

最近我一直在想这个问题，不知道用什么方法进行解决，目前考虑的仅仅是文件夹打包，没有使用`seajs`或`requirejs`等

**Comment by Jeff2Ma** [comment]
this project is not maintained anymore.
